### ISSUE TITLE
設定為 LT(layer, key) 的按鍵在重新 connect keyboard 後，讀成  (KC_NO)

### ISSUE THREAD

**Issue by dinowchang** [ErgoKB/Ashes_issue#2]
系統：Win10
瀏覽器：Chrome

若按鍵設定為 LT(layer, key)
重新連上 Ashes 再 Connect Keyboard 後
讀到的按鍵功能變成 (KC_NO)

**Comment by LSChyi** [comment]
您好，非常感謝 bug report，已經修正並且 deploy

**Comment by LSChyi** [comment]
This issue will be closed, if found any related bug, please commit and reopen it, thank you.
