### ISSUE TITLE
Modifiers 可自由搭配

### ISSUE THREAD

**Issue by jenhausu** [ErgoKB/Ashes_issue#3]
好像不是所有組合都有，發現少了 gui + ctrl、gui + alt 這兩種組合。

**Comment by LSChyi** [comment]
您好，這是 QMK 支援的所有 keycode:

https://beta.docs.qmk.fm/using-qmk/simple-keycodes/keycodes#modifiers-id-modifiers

以上列出的組合鍵並未在列表中

請問是在哪裡看到或需要使用這樣的功能呢？我們目前主要以 QMK 原始功能為主，extended 的 keycode 我們可以考慮增加，但會考量其他因素

**Comment by jenhausu** [comment]
喔喔 瞭解 
我平常用的的快捷鍵不少是這些組合成的
之前在用 Ergodox EZ 時有這個功能，四個 Modifier 都可以隨意組合

**Comment by LSChyi** [comment]
因設計邏輯不同，將維持目前的設計。未來再考慮如何設計成可自由搭配四顆 modifier。Ticket 會被重新命名

**Comment by LSChyi** [comment]
嗨，我們已經開放 Phoenix 可以使用新版的 remap 設定器，當中已包含可自由搭配各種 modifier，請依照[升級教學](https://www.ergokb.tw/products/phoenix/upgrade.html)升級 Phoenix 韌體，即可進入 https://remap.ergokb.tw/ 使用此功能，謝謝
