### ISSUE TITLE
新增 Mod-Tap Keys 和 LM 

### ISSUE THREAD

**Issue by dinowchang** [ErgoKB/Ashes_issue#4]
希望新增 LM(layer, mod) 鍵和 Mod-Tap 系列的按鍵

**Comment by LSChyi** [comment]
Please follow the format of `Feature request` template

**Comment by LSChyi** [comment]
嗨，我們已經開放 Phoenix 可以使用新版的 remap 設定器，當中已包含`LM` 功能 ）(於 Search Keycode 中使用) 和Mod-Tap 功能 (於 HOLD/TAP tab 設定) ，請依照[升級教學](https://www.ergokb.tw/products/phoenix/upgrade.html)升級 Phoenix 韌體，即可進入 https://remap.ergokb.tw/ 使用此功能，謝謝
