### ISSUE TITLE
新增 SH_ON key 設定

### ISSUE THREAD

**Issue by guesslin** [ErgoKB/Ashes_issue#5]
有時候會只使用單邊的手打字，這時候會讓單邊的手（例如：右手）繞過去使用另一邊的鍵盤。 

在 Ashes 鍵位設定器啟用 QMK 的 swap hands 功能 [See Swap Hands - QMK](https://beta.docs.qmk.fm/using-qmk/software-features/feature_swap_hands) ，如果需要的話並提供韌體更新。

**Comment by LSChyi** [comment]
已編譯於新版韌體中，並且於新版 remap configurator 中加入
